services:
  eshopdb:
    image: postgres

  distributed-cache:
    image: redis

  seq:
    image: datalust/seq:latest

  message-bus:
    image: rabbitmq:management

  identity:
    image: keycloak/keycloak

volumes:
  postgres_eshopdb: